config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create]

  resources :wikis
  resources :collaborations, only: [:new, :create, :destroy]
  devise_for :users

  authenticated :user do
   root 'wikis#index', as: :authenticated_root
  end

  put '/downgrade', to: 'charges#downgrade'

  root 'welcome#index'
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user_id = current_user[:id]
    @wiki.private = params[:wiki][:private]

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user_id = 1
    @wiki.private = false

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    authorize Wiki
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/edit.html.erb
<h1>Update wiki</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
    <%= link_to "Add Collaborator", new_collaboration_path(wiki_id: @wiki.id), class: 'btn btn-success' %>
    <div>
      <h3>Existing Collaborations:</h3>
    </div>
    <% @wiki.collaborations.each do |collaboration| %>
      <div>
        <%= collaboration.user.email %>
        <%= link_to "Delete Collaboration", collaboration, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this collaboration?'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
 <h1>Wikis</h1>
 <% @wikis.each do |wiki| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>
 <% end %>
 <%= link_to "Create New Wiki", new_wiki_path, class: "btn btn-success wikibtn" %>

app/views/wikis/new.html.erb
<h1>Create new wiki</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<div>
  <a href="/wikis" class="btn btn-primary wikibtn">Back to all Wikis</a>
</div>
<h1><%= markdown(@wiki.title) %></h1>
<p><%= markdown(@wiki.body) %></p>
<p>Submitted by <%= @wiki.user.email %></p>
<%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>